-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 20:02:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_INVICTO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_INVICTO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_INVICTO` DEFAULT CHARACTER SET utf8 ;
USE `DB_INVICTO` ;

-- -----------------------------------------------------
-- Table `DB_INVICTO`.`TB_UNIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_INVICTO`.`TB_UNIDADE` (
  `id_unidade` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL COMMENT 'Endereço não pode ser repetido.',
  `situacao` TINYINT NOT NULL DEFAULT 1 COMMENT 'USADO PARA EXCLUSÃO LÓGICA - 0 desativada 1 ativa',
  PRIMARY KEY (`id_unidade`),
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_INVICTO`.`TB_TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_INVICTO`.`TB_TURMA` (
  `id_turma` BIGINT NOT NULL AUTO_INCREMENT,
  `unidade_id` BIGINT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `situacao` TINYINT NOT NULL DEFAULT 1 COMMENT 'USADO PARA EXCLUSÃO LÓGICA - 0 desativada 1 ativa',
  PRIMARY KEY (`id_turma`),
  INDEX `FK_TB_TURMA_TB_UNIDADE_IDX` (`unidade_id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  CONSTRAINT `fk_TB_TURMA_TB_UNIDADE1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `DB_INVICTO`.`TB_UNIDADE` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_INVICTO`.`TB_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_INVICTO`.`TB_ALUNO` (
  `id_aluno` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `orgao_exp` VARCHAR(45) NOT NULL,
  `uf_rg` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `residencial` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pai` VARCHAR(45) NOT NULL,
  `mae` VARCHAR(45) NOT NULL,
  `situacao` TINYINT NOT NULL DEFAULT 1 COMMENT 'USADO PARA EXCLUSÃO LÓGICA - 0 desativado 1 ativo',
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_INVICTO`.`TB_CONTRATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_INVICTO`.`TB_CONTRATO` (
  `id_contrato` BIGINT NOT NULL AUTO_INCREMENT,
  `aluno_id` BIGINT NOT NULL,
  `turma_id` BIGINT NOT NULL,
  `taxa_matricula` DOUBLE NOT NULL,
  `valor_curso` DOUBLE NOT NULL,
  `desconto_curso` DOUBLE(3,2) NOT NULL COMMENT 'DE O ATÉ 100 %',
  `qtd_parcelas_curso` TINYINT(4) NOT NULL COMMENT '1 =  AVISTA, x = NUMERO DE PARCELAS \nobs ACIMA DE 2 JÁ É PARCELADO',
  `valor_material` DOUBLE NOT NULL,
  `qtd_parcelas_material` TINYINT(4) NOT NULL COMMENT '1 =  AVISTA, x = NUMERO DE PARCELAS \nobs ACIMA DE 2 JÁ É PARCELADO',
  `dia_vencimento` TINYINT NOT NULL COMMENT 'APENAS O DIA\n1,5,10 etc.',
  `forma_pagamento` VARCHAR(45) NOT NULL COMMENT '1= DINHEIRO, 2= CARTAO-CREDITO, 3= CARTAO-DEBITO, 4= CHEQUE',
  `data_matricula` DATE NOT NULL,
  `situacao` TINYINT NOT NULL DEFAULT 1 COMMENT 'USADO PARA EXCLUSÃO LÓGICA -\n0 desativado 1 ativo 2 EM ACORDO 3 ENCERRADO 4 SIMULAÇÃO',
  `matricula` VARCHAR(45) NOT NULL COMMENT 'cpf+turma+data_matricula',
  `condicao_contrato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`turma_id`, `aluno_id`),
  INDEX `FK_TB_CONTRATO_TB_ALUNO_IDX` (`aluno_id` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `FK_TB_CONTRATO_TB_TURMA_IDX` (`turma_id` ASC) INVISIBLE,
  UNIQUE INDEX `id_contrato_UNIQUE` (`id_contrato` ASC) VISIBLE,
  CONSTRAINT `fk_TB_CONTRATO_TB_ALUNO`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `DB_INVICTO`.`TB_ALUNO` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_CONTRATO_TB_TURMA`
    FOREIGN KEY (`turma_id`)
    REFERENCES `DB_INVICTO`.`TB_TURMA` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = REDUNDANT;


-- -----------------------------------------------------
-- Table `DB_INVICTO`.`TB_PARCELA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_INVICTO`.`TB_PARCELA` (
  `id_parcela` BIGINT NOT NULL AUTO_INCREMENT,
  `contrato_id` BIGINT NOT NULL,
  `numero_parcela_curso` TINYINT NOT NULL COMMENT 'PARCELA DE NUMERO 1 PARCELA DE NUMERO 2 E ETC..',
  `numero_parcela_material` TINYINT NOT NULL COMMENT '\'PARCELA DE NUMERO 1 PARCELA DE NUMERO 2 E ETC..\'',
  `data_vencimento` DATE NOT NULL,
  `valor_pago` DECIMAL(7,2) NULL COMMENT '\'VALOR PAGO NESTA DATA\'',
  `data_pagamento` DATE NULL,
  `valor_parcela_curso` DECIMAL(7,2) NOT NULL COMMENT 'VALOR COM DESCONTO E PARCELADO',
  `valor_parcela_material` DECIMAL(7,2) NOT NULL COMMENT 'VALOR PARCELADO',
  `valor_total_parcela` DECIMAL(7,2) NOT NULL COMMENT 'PARCELA_CURSO+PARCELA_MATERIAL+TAXA_MATRICULA',
  `situacao_parcela` VARCHAR(20) NOT NULL COMMENT '1= PAGO, 2 = A VENCER, 3 = ATRASADO 4 = CANCELADO POR ACORDO',
  `numero_parcela` TINYINT NOT NULL COMMENT 'a primeira parcela contem a 1ª parcela de curso + 0ª parcela de Material. Na segunda parcela contem a 2ª parcela de curso + 1ª parcela de Material. Na terceira parcela contem a 3ª parcela de curso + 2ª parcela de Material e etc..',
  `taxa_matricula` DECIMAL(7,2) NOT NULL,
  `valor_residual_curso` DECIMAL(7,2) NOT NULL,
  `valor_residual_material` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_parcela`),
  INDEX `FK_PARCELAS_MATRICULA_IDX` (`contrato_id` ASC) VISIBLE,
  CONSTRAINT `fk_PARCELAS_MATRICULA1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `DB_INVICTO`.`TB_CONTRATO` (`id_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
