select * from tb_despesa

SELECT * FROM TB_CATEGORIA

SELECT
C.NOME, C.TIPO_CATEGORIA,
F.NOME, F.MATRICULA, F.CARGO,
D.ID_DESPESA, D.FUNCIONARIO_ID, D.CATEGORIA_ID, D.VALOR_DESPESA, D.DIA_VENCIMENTO, D.VIA_RECEBIDO

FROM
TB_DESPESA AS D
LEFT JOIN TB_FUNCIONARIO AS F ON D.FUNCIONARIO_ID = F.ID_FUNCIONARIO
INNER JOIN TB_CATEGORIA AS C ON D.CATEGORIA_ID = C.ID_CATEGORIA;

--RIGHT JOIN TB_CATEGORIA AS C ON D.CATEGORIA_ID = C.ID_CATEGORIA;

SELECT
				C.NOME, C.TIPO_CATEGORIA,
				F.NOME, F.MATRICULA, F.CARGO,
				D.ID_DESPESA, D.FUNCIONARIO_ID, D.CATEGORIA_ID, D.VALOR_DESPESA, D.DIA_VENCIMENTO, D.VIA_RECEBIDO
				 
				FROM
				TB_DESPESA AS D,
				TB_CATEGORIA AS C,
				TB_FUNCIONARIO AS F

				WHERE
				D.CATEGORIA_ID = C.id_categoria
				AND
				D.FUNCIONARIO_ID = F.id_funcionario
				AND 
				D.ATIVO = 1;

				INSERT INTO TB_DESPESA (categoria_id, funcionario_id, valor_despesa, dia_vencimento, via_recebido, ativo)
				values (9,null,1000,15,'correios',1);

				